apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment.fullname" . }}
  labels:
    app: payment-service
    version: {{ .Chart.AppVersion | quote }}
data:
  DD_SERVICE: {{ .Values.datadog.service | quote }}
  DD_ENV: {{ .Values.datadog.env | quote }}
  DD_VERSION: {{ .Values.datadog.version | quote }}
  DD_TRACE_ENABLED: {{ .Values.datadog.traceEnabled | quote }}
  DD_AGENT_HOST: {{ .Values.datadog.agentHost | quote }}
  DD_AGENT_PORT: "8126"
